## hw 02

In [1]:
import numpy as np

In [6]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
B = np.array([[9,10],[11,12],[13,14],[15,16]])
print(A)
print(A.shape)
print(B)
print(B.shape)
print(A.dot(B))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]
(4, 2)


ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [8]:
A = np.array([[1,2,3,4,5],[6,7,8,9,10]])
B = np.array([[9,10,11],[11,12,13],[13,14,15],[15,16,17],[17,18,19]])
print(A)
print(A.shape)
print(B)
print(B.shape)
print(A.dot(B))
print((A.dot(B)).shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
[[ 9 10 11]
 [11 12 13]
 [13 14 15]
 [15 16 17]
 [17 18 19]]
(5, 3)
[[215 230 245]
 [540 580 620]]
(2, 3)


In [9]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21],[22,23,24]])
B = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16],[17,18,19,20,21,22,23,24]])
print(A)
print(A.shape)
print(B)
print(B.shape)
print(A.dot(B))
print((A.dot(B)).shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]
(8, 3)
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
(3, 8)
[[  70   76   82   88   94  100  106  112]
 [ 151  166  181  196  211  226  241  256]
 [ 232  256  280  304  328  352  376  400]
 [ 313  346  379  412  445  478  511  544]
 [ 394  436  478  520  562  604  646  688]
 [ 475  526  577  628  679  730  781  832]
 [ 556  616  676  736  796  856  916  976]
 [ 637  706  775  844  913  982 1051 1120]]
(8, 8)


In [10]:
A = np.eye(4)
B = np.eye(4)
print(A)
print(A.shape)
print(B)
print(B.shape)
print(A.dot(B))
print((A.dot(B)).shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [11]:
A = np.array([[1,-2],[3,0]])
B = np.array([[4,-1],[0,5]])
print(A)
print(A.shape)
print(B)
print(B.shape)
print(A.dot(B))
print((A.dot(B)).shape)
print(A + B)
print((A + B).shape)

[[ 1 -2]
 [ 3  0]]
(2, 2)
[[ 4 -1]
 [ 0  5]]
(2, 2)
[[  4 -11]
 [ 12  -3]]
(2, 2)
[[ 5 -3]
 [ 3  5]]
(2, 2)


In [14]:
A = np.array([[1,7],[3,-6]])
B = np.array([[0,5],[2,-1]])
C = np.array([[2,-4],[1,1]])
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

In [15]:
A = np.array([[4,1],[5,-2],[2,3]])
print(A.dot(A.T))
print((A.T).dot(A))

[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


In [16]:
A = [[1,7],[3,-6]]
B = [[0,5],[2,-1]]

## методичка 4

In [17]:
A = np.array([[4,2,3],[0,5,1],[0,0,9]])
np.linalg.det(A)

180.0

In [20]:
a=30
A = np.array([[np.sin(a), -np.cos(a)],[np.cos(a), np.sin(a)]])
np.linalg.det(A)

1.0

In [21]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(A)

-9.51619735392994e-16

In [22]:
A = np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
np.linalg.det(A)

0.0

In [23]:
A = np.array([[1,2,3],[1,1,1],[2,3,4]])
np.linalg.matrix_rank(A)

2

In [24]:
A = np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
np.linalg.matrix_rank(A)

3

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$ = 16 для квадратных матриц
    
   б) $det(A^{T})$ = 4
    
   в) $det(2A)$ = невозможно сказать, зависит от размена