In [1]:
import numpy as np

## 1

In [2]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
print(w)
print()
print(v)

[2. 3.]

[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


## 2

Поскольку заданная матрица разворачивает вектор на 180 градусов, то любой вектор после её преобразования будет коллиниарен исходному, и так же может быть получен умножением на -1

## 3

In [3]:
a = np.array([[1,1], [-1,3]])
x = np.array([1,1])
a.dot(x)

array([2, 2])

Вектор (1,1) является собственным вектором, поскольку (2,2) так же может быть получен из исходного умножением на 2

## 4

In [4]:
a = np.array([[0,3,0], [3,0,0], [0,0,3]])
x = np.array([3,-3,-4])
a.dot(x)

array([ -9,   9, -12])

Вектор [3,-3,-4] не является собственным, так как не существует λ, удовлетворяющего равенству Ax=λx