import numpy as np
from numpy.linalg import matrix_rank

# 2

## a

In [6]:
A = np.array([[3,-1,1],[2,-5,-3],[1,1,-1]])
b = np.array([[4,-17,0]])
augMatrix = np.concatenate((A,b.T), axis=1)
augMatrix

array([[  3,  -1,   1,   4],
       [  2,  -5,  -3, -17],
       [  1,   1,  -1,   0]])

In [11]:
print(matrix_rank(augMatrix))
print(matrix_rank(A))

3
3


поскольку ранг матрицы равен рангу расширенной матрицы и равен количеству неизвестных, то система будет иметь одно единственное решение

## b

In [14]:
A = np.array([[2,-4,6],[1,-2,3],[3,-6,9]])
b = np.array([[1,-2,5]])
augMatrix = np.concatenate((A,b.T), axis=1)
augMatrix

array([[ 2, -4,  6,  1],
       [ 1, -2,  3, -2],
       [ 3, -6,  9,  5]])

In [16]:
print(matrix_rank(augMatrix))
print(matrix_rank(A))

2
1


поскольку ранг матрицы не равен рангу расширенной матрицы, то система решений не имеет

## c

In [17]:
A = np.array([[1,2,5],[3,1,-8]])
b = np.array([[4,-2]])
augMatrix = np.concatenate((A,b.T), axis=1)
augMatrix

array([[ 1,  2,  5,  4],
       [ 3,  1, -8, -2]])

In [19]:
print(matrix_rank(augMatrix))
print(matrix_rank(A))

2
2


ранг матрицы равен рангу расширенной матрицы, но меньше количества неизвестных, значит система имеет бесконечное количество решений

# 3

In [20]:
A = np.array([[1,3,-2,4],[0,5,0,1],[0,0,3,0],[0,0,0,2]])
b = np.array([[3,2,4,1]])
augMatrix = np.concatenate((A,b.T), axis=1)
augMatrix

array([[ 1,  3, -2,  4,  3],
       [ 0,  5,  0,  1,  2],
       [ 0,  0,  3,  0,  4],
       [ 0,  0,  0,  2,  1]])

In [22]:
print(matrix_rank(augMatrix))
print(matrix_rank(A))

4
4


поскольку ранг матрицы равен рангу расширенной матрицы и равен количеству неизвестных, то система будет иметь одно единственное решение

# 4

In [32]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,4]])
augMatrix = np.concatenate((A,b.T), axis=1)
augMatrix

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 4]])

In [33]:
print(matrix_rank(augMatrix))
print(matrix_rank(A))

3
2


система не имеет решений при a - 2b + c != 0